# Generated by Django 5.1.5 on 2025-03-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_alter_screen_theater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='movie',
        ),
    ]
