# Generated by Django 5.1.5 on 2025-03-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, help_text='Poll end date', null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='movie_planned_release_date',
            field=models.DateField(blank=True, help_text='Movie release date if the poll have enough yes votes', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='decision',
            field=models.BooleanField(blank=True, default=False, help_text='True if movie will be released', null=True),
        ),
    ]
