# Generated by Django 5.1.5 on 2025-03-10 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('polls', '0003_poll_end_date_poll_movie_planned_release_date_and_more'),
        ('theaters', '0002_alter_screen_theater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='movie_planned_release_date',
        ),
        migrations.AddField(
            model_name='poll',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.screen'),
        ),
        migrations.AddField(
            model_name='poll',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theaters.theater'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='decision',
            field=models.BooleanField(blank=True, default=None, help_text='True if movie will be released', null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
